### ISSUE TITLE
The wrong in highlight line numbers in the theme of vim and more

### ISSUE THREAD

**Issue by Comdex** [n1k0/SublimeHighlight#46]
When I use the theme of vim such as black background ,I found that the exported html has wrong with highlight linenumbers .Those line numbers can't be seen cleary because
the color is not perfect,Can the theme be change perfect?

**Comment by kgizdov** [comment]
[This line](https://github.com/n1k0/SublimeHighlight/blob/a3e060ec2c7eea7c476ddd52ffbefde8b6be5d70/pygments/formatters/html.py#L66) and [the next](https://github.com/n1k0/SublimeHighlight/blob/a3e060ec2c7eea7c476ddd52ffbefde8b6be5d70/pygments/formatters/html.py#L67) are the culprit. Line background is set fixed and not taken from the theme. This is a bug.

@n1k0 could you have a look. It looks very bad with monokai them for example.

**Comment by n1k0** [comment]
Fixed by #66
